import Head from "next/head";
import TourCard from "../components/TourCard";
import {Grid} from "@mui/material";
import {Paper} from "@mui/material";
import { Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container>
          <Grid item sm={6} xs={12} md={3}>
            <Paper>1</Paper>
          </Grid>
          <Grid item sm={6} xs={12} md={3}>
            <Paper>2</Paper>
          </Grid>
          <Grid item sm={6} xs={12} md={3}>
            <Paper>3</Paper>
          </Grid>
          <Grid item sm={6} xs={12} md={3}>
            <Paper>4</Paper>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
